export const evisaWebsitesMap = new Map();

evisaWebsitesMap.set("Armenia", "https://evisa.mfa.am/")
evisaWebsitesMap.set("Azerbaijan", "https://evisa.gov.az/en/")
evisaWebsitesMap.set("Australia", "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/electronic-travel-authority-601")
evisaWebsitesMap.set("Bahrain", "https://www.evisa.gov.bh/")
evisaWebsitesMap.set("Ivory Coast", "https://www.cotedivoire.online/en/")
evisaWebsitesMap.set("Egypt","https://visa2egypt.gov.eg/eVisa")
evisaWebsitesMap.set("Indonesia","https://molina.imigrasi.go.id/#:~:text=e%2DVOA%20is%20a%20visa,Good%20Purchasing")
evisaWebsitesMap.set("India","https://indianvisaonline.gov.in/evisa/tvoa.html")
evisaWebsitesMap.set("Kenya","https://evisa.go.ke/")
evisaWebsitesMap.set("East Africa","https://evisa.go.ke/east-african-tourist-visa.html")
evisaWebsitesMap.set("Cambodia","https://www.evisa.gov.kh/")
evisaWebsitesMap.set("South Korea","https://www.k-eta.go.kr/portal/apply/index.do")
evisaWebsitesMap.set("Laos","https://laoevisa.gov.la/index")
evisaWebsitesMap.set("Sri Lanka","https://www.eta.gov.lk/slvisa/visainfo/center.jsp?locale=en_US")
evisaWebsitesMap.set("Myanmar","https://evisa.moip.gov.mm/")
evisaWebsitesMap.set("Nepal","https://www.immigration.gov.np/page/visa-on-arrival")
evisaWebsitesMap.set("New Zealand","https://nzeta.immigration.govt.nz/")
evisaWebsitesMap.set("Oman","https://evisa.rop.gov.om/")
evisaWebsitesMap.set("Papau New Guinea","https://evisa.ica.gov.pg/evisa/account/Apply?ReturnUrl=%2fevisa%2f")
evisaWebsitesMap.set("Saudi Arabia","https://visa.visitsaudi.com/")
evisaWebsitesMap.set("Togo","https://voyage.gouv.tg/")
evisaWebsitesMap.set("Türkiye","https://www.evisa.gov.tr/")
    // "Tanzania":"https://eservices.immigration.go.tz/visa/",
    // "Uganda":"https://visas.immigration.go.ug/",
    // "":"",
evisaWebsitesMap.set("Uzbekistan","https://e-visa.gov.uz/main")
evisaWebsitesMap.set("Vietnam","https://evisa.xuatnhapcanh.gov.vn/trang-chu-ttdt")
evisaWebsitesMap.set("Zimbabwe","https://www.evisa.gov.zw/")