const evisaWebsitesMap = {
    "Armenia":"https://evisa.mfa.am/",
    "Azerbaijan":"https://evisa.gov.az/en/",
    "Australia":"https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/electronic-travel-authority-601",
    "Bahrain":"https://www.evisa.gov.bh/",
    "Ivory Coast": "https://www.cotedivoire.online/en/",
    "Egypt":"https://visa2egypt.gov.eg/eVisa",
    "Indonesia":"https://molina.imigrasi.go.id/#:~:text=e%2DVOA%20is%20a%20visa,Good%20Purchasing",
    "India":"https://indianvisaonline.gov.in/evisa/tvoa.html",
    "Kenya":"https://evisa.go.ke/",
    "East Africa":"https://evisa.go.ke/east-african-tourist-visa.html",
    "Cambodia":"https://www.evisa.gov.kh/",
    "South Korea":"https://www.k-eta.go.kr/portal/apply/index.do",
    "Laos":"https://laoevisa.gov.la/index",
    "Sri Lanka":"https://www.eta.gov.lk/slvisa/visainfo/center.jsp?locale=en_US",
    "Myanmar":"https://evisa.moip.gov.mm/",
    "Nepal":"https://www.immigration.gov.np/page/visa-on-arrival",
    "New Zealand":"https://nzeta.immigration.govt.nz/",
    "Oman":"https://evisa.rop.gov.om/",
    "Papau New Guinea":"https://evisa.ica.gov.pg/evisa/account/Apply?ReturnUrl=%2fevisa%2f",
    "Saudi Arabia":"https://visa.visitsaudi.com/",
    "Togo":"https://voyage.gouv.tg/",
    "Türkiye":"https://www.evisa.gov.tr/",
    // "Tanzania":"https://eservices.immigration.go.tz/visa/",
    // "Uganda":"https://visas.immigration.go.ug/",
    // "":"",
    "Uzbekistan":"https://e-visa.gov.uz/main",
    "Vietnam":"https://evisa.xuatnhapcanh.gov.vn/trang-chu-ttdt",
    "Zimbabwe":"https://www.evisa.gov.zw/"

}