export const passportDemonyms = new Map([
    ['af', 'Afghan'],
    ['al', 'Albanian'],
    ['dz', 'Algerian'],
    ['ad', 'Andorran'],
    ['ao', 'Angolan'],
    ['ai', 'Anguillan'],
    ['aq', 'Antarctican'],
    ['ag', 'Antiguan'],
    ['ar', 'Argentinian'],
    ['am', 'Armenian'],
    ['aw', 'Arubian'],
    ['au', 'Australian'],
    ['at', 'Austrian'],
    ['az', 'Azerbaijani'],
    ['bs', 'Bahamian'],
    ['bh', 'Bahraini'],
    ['bd', 'Bangladeshi'],
    ['bb', 'Barbadian'],
    ['by', 'Belarusian'],
    ['be', 'Belgian'],
    ['bz', 'Belizean'],
    ['bj', 'Beninese'],
    ['bm', 'Bermudian'],
    ['bt', 'Bhutanese'],
    ['bo', 'Bolivian'],
    ['ba', 'Bosnian'],
    ['bw', 'Botswanan'],
    ['br', 'Brazilian'],
    ['bn', 'Bruneian'],
    ['bg', 'Bulgarian'],
    ['bf', 'Burkinabe'],
    ['bi', 'Burundian'],
    ['kh', 'Cambodian'],
    ['cm', 'Cameroonian'],
    ['ca', 'Canadian'],
    ['cv', 'Cape Verdean'],
    ['ky', 'Caymanian'],
    ['cf', 'Central African'],
    ['td', 'Chadian'],
    ['cl', 'Chilean'],
    ['cn', 'Chinese'],
    ['co', 'Colombian'],
    ['km', 'Comoran'],
    ['cg', 'Congolese'],
    ['cr', 'Costa Rican'],
    ['hr', 'Croatian'],
    ['cu', 'Cuban'],
    ['cy', 'Cypriot'],
    ['cz', 'Czech'],
    ['dk', 'Danish'],
    ['dj', 'Djiboutian'],
    ['dm', 'Dominican'],
    ['do', 'Dominican'],
    ['tl', 'East Timorese'],
    ['ec', 'Ecuadorian'],
    ['eg', 'Egyptian'],
    ['sv', 'Salvadoran'],
    ['gq', 'Equatorial Guinean'],
    ['er', 'Eritrean'],
    ['ee', 'Estonian'],
    ['et', 'Ethiopian'],
    ['fj', 'Fijian'],
    ['fi', 'Finnish'],
    ['fr', 'French'],
    ['ga', 'Gabonese'],
    ['gm', 'Gambian'],
    ['ge', 'Georgian'],
    ['de', 'German'],
    ['gh', 'Ghanaian'],
    ['gr', 'Greek'],
    ['gd', 'Grenadian'],
    ['gt', 'Guatemalan'],
    ['gn', 'Guinean'],
    ['gw', 'Bissau-Guinean'],
    ['gy', 'Guyanese'],
    ['ht', 'Haitian'],
    ['hn', 'Honduran'],
    ['hk', 'Hong Kong'],
    ['hu', 'Hungarian'],
    ['is', 'Icelandic'],
    ['in', 'Indian'],
    ['id', 'Indonesian'],
    ['ir', 'Iranian'],
    ['iq', 'Iraqi'],
    ['ie', 'Irish'],
    ['il', 'Israeli'],
    ['it', 'Italian'],
    ['ci', 'Ivorian'],
    ['jm', 'Jamaican'],
    ['jp', 'Japanese'],
    ['je', 'Jersey'],
    ['jo', 'Jordanian'],
    ['kz', 'Kazakhstani'],
    ['ke', 'Kenyan'],
    ['ki', 'Kiribati'],
    ['kw', 'Kuwaiti'],
    ['kg', 'Kyrgyzstani'],
    ['la', 'Laotian'],
    ['lv', 'Latvian'],
    ['lb', 'Lebanese'],
    ['ls', 'Basotho'],
    ['lr', 'Liberian'],
    ['ly', 'Libyan'],
    ['li', 'Liechtensteiner'],
    ['lt', 'Lithuanian'],
    ['lu', 'Luxembourger'],
    ['mo', 'Macanese'],
    ['mk', 'Macedonian'],
    ['mg', 'Malagasy'],
    ['mw', 'Malawian'],
    ['my', 'Malaysian'],
    ['mv', 'Maldivian'],
    ['ml', 'Malian'],
    ['mt', 'Maltese'],
    ['mr', 'Mauritanian'],
    ['mu', 'Mauritian'],
    ['mx', 'Mexican'],
    ['fm', 'Micronesian'],
    ['md', 'Moldovan'],
    ['mc', 'Monacan'],
    ['mn', 'Mongolian'],
    ['me', 'Montenegrin'],
    ['ms', 'Montserratian'],
    ['ma', 'Moroccan'],
    ['mz', 'Mozambican'],
    ['mm', 'Burmese'],
    ['na', 'Namibian'],
    ['nr', 'Nauruan'],
    ['np', 'Nepali'],
    ['nl', 'Dutch'],
    ['nz', 'New Zealand'],
    ['ni', 'Nicaraguan'],
    ['ne', 'Nigerien'],
    ['ng', 'Nigerian'],
    ['nu', 'Niuean'],
    ['kp', 'North Korean'],
    ['no', 'Norwegian'],
    ['om', 'Omani'],
    ['pk', 'Pakistani'],
    ['pw', 'Palauan'],
    ['pa', 'Panamanian'],
    ['pg', 'Papua New Guinean'],
    ['py', 'Paraguayan'],
    ['pe', 'Peruvian'],
    ['ph', 'Philippine'],
    ['pn', 'Pitcairn Islander'],
    ['pl', 'Polish'],
    ['pt', 'Portuguese'],
    ['qa', 'Qatari'],
    ['ro', 'Romanian'],
    ['ru', 'Russian'],
    ['rw', 'Rwandan'],
    ['kn', 'Saint Kitts and Nevis'],
    ['lc', 'Saint Lucian'],
    ['pm', 'Saint Pierrian'],
    ['vc', 'Vincentian'],
    ['ws', 'Samoan'],
    ['sm', 'San Marino'],
    ['st', 'Sao Tomean'],
    ['sa', 'Saudi Arabian'],
    ['sn', 'Senegalese'],
    ['rs', 'Serbian'],
    ['sc', 'Seychellois'],
    ['sl', 'Sierra Leonean'],
    ['sg', 'Singaporean'],
    ['sk', 'Slovakian'],
    ['si', 'Slovenian'],
    ['sb', 'Solomon Islands'],
    ['so', 'Somali'],
    ['za', 'South African'],
    ['kr', 'South Korean'],
    ['ss', 'South Sudanese'],
    ['es', 'Spanish'],
    ['lk', 'Sri Lankan'],
    ['sd', 'Sudanese'],
    ['sr', 'Surinamese'],
    ['sz', 'Swazi'],
    ['se', 'Swedish'],
    ['ch', 'Swiss'],
    ['sy', 'Syrian'],
    ['tw', 'Taiwanese'],
    ['tj', 'Tajikistani'],
    ['tz', 'Tanzanian'],
    ['th', 'Thai'],
    ['tg', 'Togolese'],
    ['to', 'Tongan'],
    ['tt', 'Trinidadian'],
    ['tn', 'Tunisian'],
    ['tr', 'Turkish'],
    ['tm', 'Turkmen'],
    ['tv', 'Tuvaluan'],
    ['ug', 'Ugandan'],
    ['ua', 'Ukrainian'],
    ['ae', 'Emirati'],
    ['gb', 'British'],
    ['us', 'American'],
    ['uy', 'Uruguayan'],
    ['uz', 'Uzbekistani'],
    ['vu', 'Vanuatuan'],
    ['va', 'Vatican'],
    ['ve', 'Venezuelan'],
    ['vn', 'Vietnamese'],
    ['ye', 'Yemeni'],
    ['zm', 'Zambian'],
    ['zw', 'Zimbabwean']
    ]);
    